#!/usr/bin/env bash
#Starts Starling Server

set -e

cli_help_install() {
    echo -e "
Command: deploy (options) [command]

Deploys a given configuration file. By default, it will launch docker compose files.
However if kind is detected as running, it will apply to kubernetes

Example: deploy -f <config filepath> start

commands:
    no command\t Same as start
    start\t\tDeploy given file or container
    stop\t\tStop given file or container
    restart\t\tRestart given file or container

options:
    --file/-f\t\tSpecify config file (relative to current location or absolute)
"
}

# Check if running using starling cli
if [ -z ${STARLING_COMMON_SOURCED+'check'} ]; then
    echo "Common not sourced, please run from starling cli"
    exit 1
fi

START=1

# Parse arguments
while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        -h|--help|help)
            cli_help_install
            exit 1
            ;;
        start)
            START=1
            shift
            ;;
        stop)
            STOP=1
            unset START
            shift
            ;;
        restart)
            START=1
            STOP=1
            shift
            ;;
        -f|--file)
            FILE=$2
            shift
            shift
            ;;
        --build)
            DC_BUILD=1
            shift
            ;;
        *)  # unknown option
            echo "Unknown Argument/ Option $1"
            cli_help_install
            exit 1
            ;;
    esac
done

# Check if kubectl can find active connection otherwise use docker-compose
if  [[ "$(kubectl get pods --namespace kube-system)" ]]; then
    KUBECTL_ENABLED=1
    echo "Kubectl has connection"
else
    echo "Kubectl not detected, docker-compose to be used"
fi

if [[ ! $FILE ]]; then
    echo "Error: Must specify file using -f argument"
    exit 1
fi

if [[ $STOP ]]; then
    if [[ $KUBECTL_ENABLED ]]; then
        echo "Stopping configuration given by: $FILE"
        kubectl delete -f "$FILE"
    else
        echo "Stopping docker compose file given by $FILE"
        docker-compose -f "$FILE" down
    fi
fi

if [[ $START ]]; then
    if [[ $KUBECTL_ENABLED ]]; then
        echo "Staring configuration given by: $FILE"
        kubectl apply -f "$FILE"
    else
        echo "Starting docker compose file given by $FILE"
        if [[ $DC_BUILD ]]; then
            docker-compose -f "$FILE" up --build
        else
            docker-compose -f "$FILE" up
        fi
    fi
fi
