#!/usr/bin/env bash
#Starts Starling Server

set -e 

cli_help_install() {
    echo -e "
Command: stop [kind/k3s] (optional)

Usage:
    No Arguments\t\tStarts kubernetes and deployment only
    kind/k\t\tStarts kubernetes and starts the simulator deployment

Optional Arguments
    --name\t\tName of cluster to delete (kind)
"
}

# Check if running using starling cli
if [ -z ${STARLING_COMMON_SOURCED+'check'} ]; then
    echo "Common not sourced, please run from starling cli"
    exit 1
fi

# Parse arguments
while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        -h|--help|help)
            cli_help_install
            exit 1
            ;;
        --name)
            CLUSTER_NAME=$2
            shift
            shift
            ;;
        kind)
            S_KIND=1
            shift
            ;;
        k3s)
            S_K3S=1
            shift
            ;;
        *)  # unknown option
            echo "Unknown Argument/ Option $1"
            cli_help_install
            exit 1
            shift # past argument
            ;;
    esac
done

# Start k3s

# STOP kind
if [[ $S_KIND ]]; then
    kind delete cluster --name="${CLUSTER_NAME:-starling-cluster}"
fi



