# Default Starling Vehicle Deployments
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: starling-mavros-daemon
  labels:
    app: starling

spec:
  selector:
    matchLabels:
      name: starling-mavros-daemon

  template:
    metadata:
      labels:
        name: starling-mavros-daemon

    spec:
      nodeSelector:
        starling.dev/type: vehicle

      tolerations:
        - key: starling.dev/type
          operator: Equal
          value: vehicle
          effect: NoSchedule

      hostNetwork: true
      shareProcessNamespace: true

      containers:
        - name: starling-mavros
          image: uobflightlabstarling/starling-mavros:nightly
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
          - name: MAVROS_TGT_FIRMWARE
            value: "px4"
          - name: MAVROS_TGT_SYSTEM
            value: "auto" # Look up on system /etc/drone.config
          - name: ROS_HOSTNAME # Required for ROS1 bridge in hostNetwork mode
            value: "localhost" # ROS1 will ping HOSTNAME, defaults to system hostname
          - name: ROS_MASTER_URI
            value: "http://localhost:11311"
          # - name: ROS_DISCOVERY_SERVER
          #   value: "192.168.10.80:11811;127.0.0.1:11811"
          - name: MAVROS_GCS_URL
            value: "udp://@:14550"
          - name: BRIDGE_LAUNCH_DELAY
            value: "10"
          - name: ROS_DOMAIN_ID
            value: "2"
          volumeMounts:
          - mountPath: /dev/px4fmu
            name: ttypx4
          - mountPath: /etc/starling/vehicle.config
            name: vehicleconfig
            readOnly: true
      volumes:
        - name: ttypx4
          hostPath:
            path: /dev/px4fmu
        - name: vehicleconfig
          hostPath:
            path: /etc/starling/vehicle.config
            type: File

# docker run -it --rm --net=host -e MAVROS_TGT_FIRMWARE=px4 -e MAVROS_TGT_SYSTEM=auto -e ROS_HOSTNAME=localhost -e ROS_MASTER_URI="http://localhost:11311" \
#   -e MAVROS_GCS_URL="udp://@:14550" -e BRIDGE_LAUNCH_DELAY=10 -e ROS_DOMAIN_ID=2 -v /dev/px4fmu:/dev/px4fmu -v /etc/starling/vehicle.config:/etc/starling/vehicle.config \
#   --privileged uobflightlabstarling/starling-mavros:nightly bash

---

# Default Server Deployments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: starling-core
  labels:
    app: starling-core
spec:
  selector:
    matchLabels:
      app:  starling-core
  template:
    metadata:
      labels:
        app: starling-core
    spec:

      hostNetwork: true
      shareProcessNamespace: true

      nodeSelector:
        name: master

      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule

      containers:
      - name: ping-monitor
        image: uobflightlabstarling/ping-monitor:nightly
        imagePullPolicy: Always
        env:
        - name: ROS_DOMAIN_ID # Set Domain ID for flight arena to avoid conflicts with localnetwork traffic
          value: "2"


