# Default Starling Vehicle Deployments
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: starling-mavros-daemon
  labels:
    app: starling

spec:
  selector:
    matchLabels:
      name: starling-mavros-daemon

  template:
    metadata:
      labels:
        name: starling-mavros-daemon

    spec:
      nodeSelector:
        starling.dev/type: vehicle

      tolerations:
        - key: starling.dev/type
          operator: Equal
          value: vehicle
          effect: NoSchedule

      hostNetwork: true
      shareProcessNamespace: true

      containers:
        - name: starling-mavros
          image: uobflightlabstarling/starling-mavros:nightly
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
          - name: MAVROS_TGT_FIRMWARE
            value: "px4"
          - name: MAVROS_TGT_SYSTEM
            value: "auto" # Look up on system /etc/drone.config
          - name: ROS_HOSTNAME # Required for ROS1 bridge in hostNetwork mode
            value: "localhost" # ROS1 will ping HOSTNAME, defaults to system hostname
          - name: ROS_MASTER_URI
            value: "http://localhost:11311"
          - name: ROS_DISCOVERY_SERVER
            value: ""
          - name: BRIDGE_LAUNCH_DELAY
            value: "9"
          volumeMounts:
          - mountPath: /dev/px4fmu
            name: ttypx4
          - mountPath: /etc/starling/vehicle.config
            name: vehicleconfig
            readOnly: true

      volumes:
        - name: ttypx4
          hostPath:
            path: /dev/px4fmu
        - name: vehicleconfig
          hostPath:
            path: /etc/starling/vehicle.config
            type: File

---

# Default Server Deployments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: starling-core
  labels:
    app: starling-core
spec:
  selector:
    matchLabels:
      app:  starling-core
  template:
    metadata:
      labels:
        app: starling-core
    spec:

      hostNetwork: true
      shareProcessNamespace: true

      hostname: starling-core
      subdomain: ros2-discovery-service

      nodeSelector:
        name: master

      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule

      containers:
      - name: ros2-discovery-server
        image: ros:foxy-ros-core
        imagePullPolicy: Always
        args: ["fastdds", "discovery", "-i", "0"]
        ports:
        - containerPort: 11811
      - name: ping-monitor
        image: uobflightlabstarling/ping-monitor:latest
        imagePullPolicy: Always
        env:
        - name: ROS_DISCOVERY_SERVER
          value: "127.0.0.1:11811"
        command: ["/bin/bash"]
        args: ["-c", "sleep 30 ; echo sleep ended ; exec /ros_ws/run.sh"]

